stages:
- prepare

variables:
  DOCKER_FILE: Dockerfile
  DOCKER_TAG: latest
  DOCKER_IMAGE: ${CI_REGISTRY_IMAGE}
  IMAGE: ${CI_REGISTRY_IMAGE}
  FF_GITLAB_REGISTRY_HELPER_IMAGE: 1

# Stage: prepare
##############################################################################

.prepare:docker: &prepare_docker
  stage: prepare
  image:
    name: docker
  variables:
    _BUILDAH_STARTED_IN_USERNS: ""
    BUILDAH_ISOLATION: chroot
    BUILDAH_LAYERS: "true"
  before_script:
  - docker version
  - docker login --username "${CI_REGISTRY_USER}" --password "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
  script:
  - docker build --no-cache --target toolchain -f ${DOCKER_FILE} -t ${DOCKER_IMAGE}:${DOCKER_TAG} .
  - docker push ${DOCKER_IMAGE}:${DOCKER_TAG}
  tags:
  - docker

prepare:docker:
  <<: *prepare_docker
